name: mastodon
description: A starting point for Mastodon access.
version: 0.2.0
homepage: https://github.com/mykdavies/Mastodon

environment:
  sdk: '>=2.12.0 <2.18.0'

dependencies:
  oauth2: ^2.0.0
  mime: ^1.0.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  http: ^0.13.4
  http_parser: ^4.0.0

dev_dependencies:
  test: ^1.20.2
  build_runner:
  freezed: ^1.1.1
  json_serializable: ^6.1.5

